package com.bobafan;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;


@Controller // This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /demo (after Application path)
public class ReviewController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ReviewRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewReview (@RequestBody Review review) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Review r = new Review();
        r.setStoreName(review.getStoreName());
        r.setDrinkName(review.getDrinkName());
        r.setRating(review.getRating());
        r.setSugarLevel(review.getSugarLevel());
        userRepository.save(r);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Review> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
